apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vkrethv55-python 
  janus-idp.io/tekton: vkrethv55-python
  backstage.io/kubernetes-id: vkrethv55-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vkrethv55-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  